server:
  session:
    timeout: 3600
  port: 8081
spring:
  profiles:
    active: dev
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.94.8.233:3306/activiti6?useUnicode=true&useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
#    LEGACYHTML5     //代表不进行严格检验
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    cache: true

  http:
    multipart:
      max-file-size: -1
      max-request-size: -1
    activiti:
      check-process-definitions: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      activiti:
        engine:
          impl:
            persistence:
              entity: trace
